name: Actions 😎

on:
  push:
    branches:
      - main

jobs:
  build_windows:
    name: Build for Windows ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      # - name: Run tests
      #   uses: game-ci/unity-test-runner@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #   with:
      #     githubToken: ${{ secrets.TOKEN }}

      # Build for Windows
      - name: Build project for Windows
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true

      # Move and rename folders and files with elevated permissions
      - name: Move and rename output folders and files
        run: |
          sudo mv build/StandaloneWindows64 build/GrayedGame
          sudo mv build/GrayedGame/StandaloneWindows64_Data build/GrayedGame/GrayedGame_Data
          sudo mv build/GrayedGame/StandaloneWindows64.exe build/GrayedGame/GrayedGame.exe

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: GG_Studio
          path: build/GrayedGame
